
services:
  postgres:
      build:
        context: ./postgres
        dockerfile: Dockerfile
        args:
          BASETAG: "17"
      environment:
        - POSTGRES_PASSWORD=testpassword
        - POSTGRES_USER=postgres
        - POSTGRES_DB=testdb
      volumes:
        - data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      restart: "no"
  backup:
      build:
        context: ./backup
        dockerfile: Dockerfile
        args:
          BASETAG: "17"
      environment:
        - POSTGRES_HOST=postgres
        - POSTGRES_USER=backup_user
        - POSTGRES_PASSWORD=testpassword
        - SCHEDULE=@hourly
        - BACKUP_DIR=/backups
        - BACKUP_KEEP_DAYS=7
        - HEALTHCHECK_PORT=8080
        - BACKUP_ON_START=TRUE
      volumes:
        - backups:/backups
      ports:
        - "8080:8080"
      depends_on:
        - postgres
      restart: "no"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/"]
        interval: 5m
        timeout: 3s
        retries: 3
        start_period: 30s

volumes:
  data:
  backups:
