services:
  postgres:
      build:
        context: ./postgres
        dockerfile: Dockerfile
        args:
          BASETAG: "17"
      environment:
        - POSTGRES_PASSWORD=testpassword
        - POSTGRES_USER=postgres
        - POSTGRES_DB=testdb
        - BACKUP_USER_PASSWORD=backup_password
      volumes:
        - data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      restart: "no"
  backup:
      build:
        context: ./backup
        dockerfile: Dockerfile
        args:
          BASETAG: "17"
      environment:
        - POSTGRES_HOST=postgres
        - POSTGRES_USER=backup_user
        - POSTGRES_PASSWORD=backup_password
        - SCHEDULE=@hourly
        - BACKUP_DIR=/backups
        - HEALTHCHECK_PORT=8080
        - BACKUP_ON_START=TRUE
        - STORAGE_TYPE=s3
        - S3_ENDPOINT_FILE=/run/secrets/s3_endpoint
        - S3_BUCKET=backup
        - S3_ACCESS_KEY_FILE=/run/secrets/s3_access_key
        - S3_SECRET_KEY_FILE=/run/secrets/s3_secret_key
      volumes:
        - backups:/backups
      secrets:
        - s3_endpoint
        - s3_access_key
        - s3_secret_key
      ports:
        - "8080:8080"
      depends_on:
        - postgres
      restart: "no"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/"]
        interval: 5m
        timeout: 3s
        retries: 3
        start_period: 30s

volumes:
  data:
  backups:

secrets:
  s3_endpoint:
    environment: S3_ENDPOINT
  s3_access_key:
    environment: S3_ACCESS_KEY
  s3_secret_key:
    environment: S3_SECRET_KEY